Sprint 04
SysoevAndrey/MovieQuiz-ios pull request #2
Opened 2022-09-16 12:42 UTC by SysoevAndrey

Задача спринта №4 курса по iOS-разработке от Яндекс.Практикума

2022-09-16 16:34 UTC, ABashkirova requested changes
Привет, Андрей. 

Все супер, есть несколько маленьких замечаний (см ответ на платформе), комментарии к коду - опциональный

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/AppDelegate.swift
> +        sleep(1)
После сдачи этой работы этот код можно удалить

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        return question.correctAnswer
Также, вы можете использовать более короткую форму
```suggestion
       questions[safe: currentQuestionIndex]?. question.correctAnswer
```

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            image: UIImage(named: model.image) ?? UIImage(),
Хороший выход! Мне он нравится даже больше, чем вариант с не очень качественной заглушкой (например, растянутое дефолтное изображение)

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Замыкания вы будете рассматривать далее, однако советую уже сейчас использовать слабый список захвата на контроллер `[weak self] in` и обращаться к свойствам и функциям через `self?`

Содержимое действия можно вынести в отдельную функцию. 

```suggestion
        let action = UIAlertAction(title: result.buttonText, style: .default) { [weak self] _ in
            self?.restartQuiz()
        }
```

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
masksToBounds и cornerRadius не меняются в зависимости от ответа, даже более того, такие же настройки требуются при старте экрана. Поэтому эта статичная настройка должна производиться перед показом экрана единожды

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/Resources/Info.plist
> +		<string>YS Display-Thin</string>
Вашему приложению нужно всего лишь два вида шрифта, поэтому остальные строчки можно удалить

2022-09-16 16:34 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Заметьте, что здесь вы вызываете отложенный (асинхронный) код. Который исполнится через 1 секунду. 
За одну секунду пользователь может еще пару раз жмякнуть по кнопке ответа, и вы вызовете еще несколько таких отложенных функций, не контролируя счетчики верных ответов и индекс текущего вопроса. 

<img width="510" alt="Screenshot 2022-09-16 at 19 03 07" src="https://user-images.githubusercontent.com/20269264/190682543-25ce8931-a34a-41ce-93ab-f3735c967463.png">

2022-09-16 17:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private weak var textLabel: UILabel!
Тут возможно в учебнике именно такие именования даны. Однако подчеркну, что названия не отвечают пункту "Имена ваших переменных и функций отражают то, чем эти переменные и функции занимаются.". 

Лучше переименовать в то, что они содержат. Постер и текст вопроса.

2022-09-16 17:46 UTC, SysoevAndrey commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            image: UIImage(named: model.image) ?? UIImage(),
Не совсем понял) Такое решение было в теории урока, я оттуда взял `UIImage()`

2022-09-16 18:22 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            image: UIImage(named: model.image) ?? UIImage(),
😄 видимо поправили, еще недавно студенты делали что-то вроде UIImage(systemName: "remove")

2022-09-16 18:23 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet var answerButtons: [UIButton]!
internal оставлен :)

2022-09-16 18:36 UTC, ABashkirova approved these changes
Отлично! Исправления приняты!

Что еще можно поделать:

Возможно вам будет интересно подумать на тем, какие ограничения и ослабления в Auto Layout добавить, чтобы ваш макет хорошо отображался на устройствах с маленькими экранами. 

Например, не самый маленький девайс iPhone 8 теперь выглядит так:
![Simulator Screen Shot - iPhone 8 - 2022-09-16 at 21 30 05](https://user-images.githubusercontent.com/20269264/190707574-9b17be81-c685-4cc9-956f-c5fa102a982d.png)

К сожалению, ваш дизайнер не добавил вам макетов для маленьких устройств и возможно даже макетов не хватит, чтобы однозначно адаптировать верстку. Такая ситуация очень напоминает реальные проекты, поэтому предлагаю вам творчески подойти к ситуации и попробовать решить это :)

2022-09-17 06:52 UTC, SysoevAndrey commented
Кажется, что выход за границы safe area на iPhone 8 можно поправить, вот такими ограничениями:

- Выравнивание по центру вертикального стека
- Изменение leading и trailing ограничений - equal -> greater than or equal

<img width="247" alt="Screenshot 2022-09-17 at 09 52 12" src="https://user-images.githubusercontent.com/48068281/190844592-3c6b18fc-0738-42ab-9c50-2516bcedfa9e.png">
<img width="410" alt="Screenshot 2022-09-17 at 09 45 47" src="https://user-images.githubusercontent.com/48068281/190844601-9748ca71-9323-462b-8d3b-427c362241ca.png">

2022-09-17 15:49 UTC, ABashkirova commented
А отображение вопроса?

2022-09-17 19:11 UTC, SysoevAndrey commented
Действительно, почему-то лейбл сильно сжимается, но ведь нельзя ему задать минимальную высоту? 🤔
<img width="379" alt="Screenshot 2022-09-17 at 22 10 35" src="https://user-images.githubusercontent.com/48068281/190872907-367502b5-670f-4884-9a82-f46d27d627cf.png">

2022-09-18 06:59 UTC, ABashkirova commented
Нельзя :) В этом и сложность этого макета. По высоте у нас есть очень жесткие констрейнтщ на тексты и кнопки. Их нельзя уменьшать, совсем. А вот начать сжимать бы постер хотя бы на чуть-чуть. 

Вам понадобятся более хитрые констрейнты для постера, и возможно дополнительные знания. Попробуйте почитать что-нибудь про content hugging и content compression resistance priorities.

2022-09-19 08:55 UTC, SysoevAndrey commented
Удалось добиться корректного отображения на iPhone 8!

- **Vertical Stack View** _Alignment_: `Fill` -> `Center`
- **Horizontal Stack View** (лейбл "Вопрос:" и счетчик вопросов): констреинты со значением 0 leading и trailing к родительскому контейнеру Vertical Stack View
- **Horizontal Stack View** (кнопки "Нет", "Да"): констреинты со значением 0 leading и trailing к родительскому контейнеру Vertical Stack View
- **UIImageView** _Content Compression Resistance Priority_: `horizontal: 250`, `vertical: 250`
- **UIView** (контейнер для UILabel с текстом вопроса) _Content Compression Resistance Priority_: `horizontal: 1000`, `vertical: 1000`; _Content Hugging Priority_: `horizontal: 250`, `vertical: 250`

<img width="567" alt="Screenshot 2022-09-19 at 11 55 03" src="https://user-images.githubusercontent.com/48068281/190982654-5f02368b-f176-427d-9df6-1989fbfae605.png">

2022-09-19 09:37 UTC, ABashkirova commented
Выглядит отлично, вы молодец!

Еще вспомнила: ориентация портретная и статус бар прозрачный.

2022-09-19 09:47 UTC, SysoevAndrey commented
Готово! ✅

<img width="584" alt="Screenshot 2022-09-19 at 12 47 31" src="https://user-images.githubusercontent.com/48068281/190991795-58188f3d-c328-4724-bd82-9ad5b94fea12.png">

2022-09-19 09:59 UTC, ABashkirova approved these changes
final aprove!

2022-09-19 10:04 UTC, merged