Sprint 06
SysoevAndrey/MovieQuiz-ios pull request #4
Opened 2022-10-14 13:43 UTC by SysoevAndrey

**Задание по спринту № 6 курса iOS-разработчик от Яндекс Практикума.**
Приложение получает список фильмов из API IMDb при начальной загрузке. При возникновении ошибки показывается алерт с ошибкой.

https://user-images.githubusercontent.com/48068281/195861713-9b0659f6-e4cc-42d6-8705-35b0c01fc8e4.mp4

2022-10-14 17:49 UTC, ABashkirova requested changes
Очень круто! Есть два предложения для доработки

2022-10-14 17:49 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
private

2022-10-14 17:49 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Можно использовать свойство hidesWhenStopped у activityIndicator, тогда не придется вручную регулировать isHidden

2022-10-14 17:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didLoadDataFromServer()
Было бы здорово, надеяться на качественно спроектированный API. Однако тут нас подстерегает не совсем ожидаемое поведение: сервис может вернуть ошибку MostPopularMovies.errorMessage и пустой список фильмов. 

Тогда ваше приложение будет думать что все загрузилось, а пользователь останется в логическом тупике. Предлагаю обработать это поведение 👍

2022-10-14 17:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +            }
👍

2022-10-14 17:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
К сожалению, если вы попадете в эту ветку, то вопрос останется без картинки и пользователь не сможет увидеть фильм, а значит и ответить верно. 

Здесь бы прекратить собирать вопрос, а выйти и показать ошибку.

2022-10-15 10:31 UTC, SysoevAndrey commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didLoadDataFromServer()
Добавил обработку этого случая, но на уровне сервиса MoviesLoader, там сработает `handler(.failure(...))`

2022-10-15 10:34 UTC, SysoevAndrey commented
Добавил обработку ошибок в уязвимых местах, но не понимаю, как обработать кейсы приватных енамов и показать пользователю читаемую ошибку, а не какую-то системную строчку

<img width="358" alt="Screenshot 2022-10-15 at 12 32 45" src="https://user-images.githubusercontent.com/48068281/195981875-6e1375d8-b4e1-456f-ba83-409a914346f0.png">

2022-10-15 11:08 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                }
тут вот аккуратно надо следить, куда выполнение программы идет дальше. 
В вашем случае - сразу дособирает вопрос и вернет его без картинки в приложение 
```suggestion
                DispatchQueue.main.async { [weak self] in
                    self?.delegate?.didFailToLoadData(with: QuestionError.imageError)
                }
                return
```

2022-10-15 11:10 UTC, ABashkirova commented
> Добавил обработку ошибок в уязвимых местах, но не понимаю, как обработать кейсы приватных енамов и показать пользователю читаемую ошибку, а не какую-то системную строчку

Обычно собирают некоторые типы интернет ошибок в приложении, описывают их отдельным enum-ом на уровне приложения, и с редакторами придумывают как именно пользователю ту или иную ошибку описать. 

Вы правы, стандартная ошибка из сервиса выглядит страшноватенькая и показывать пользователю ее – плохой тон :)

2022-10-15 11:10 UTC, ABashkirova approved these changes
🔥

2022-10-15 11:10 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                    }
👍

2022-10-15 17:26 UTC, SysoevAndrey commented
> > Добавил обработку ошибок в уязвимых местах, но не понимаю, как обработать кейсы приватных енамов и показать пользователю читаемую ошибку, а не какую-то системную строчку
> 
> Обычно собирают некоторые типы интернет ошибок в приложении, описывают их отдельным enum-ом на уровне приложения, и с редакторами придумывают как именно пользователю ту или иную ошибку описать.
> 
> Вы правы, стандартная ошибка из сервиса выглядит страшноватенько и показывать пользователю ее – плохой тон :)

Так это нужно исправлять или можно так мерджить? :)

2022-10-15 17:36 UTC, ABashkirova commented
Можно и так :)

2022-10-15 17:38 UTC, merged